services:
  app1:
    image: app1:v1
    container_name: my_app1
    depends_on:
      redis:
        condition: service_healthy

  app2:
    image: app2:v1
    container_name: my_app2
    depends_on:
      app1:
        condition: service_completed_successfully

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5